version: "3.8"
services:
  postgres:
    image: grafana/grafana-oss:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - "grafana-storage:/var/lib/grafana"
    networks:
      - db-network

networks:
  db-network:
    name: db-network
    driver: bridge

volumes:
  grafana-storage:
